function [Vout,I_new] = interogator(I_stim)
    
    %%%%Automatic functioning of interogator: 
    %%%%Stimulates Electrode 1 if AP generated is lesser than required
    %%%%threshold stimulates Electrode 2 which generates higher AP of the
    %%%%AP generated by the second electrode is not above the required
    %%%%threshold stimulates both electrodes simultaneouly and if still the
    %%%%AP is below a threshold then increases I stimulus

    V_th = 90;%mV
    ipi = 100;%%usec
    pulse_width = 500;%%usec
    dur = 10;
    dt = 0.001;
    
    V_tot1 = electrod1_stim(I_stim,ipi,pulse_width,dur,dt);
    Vmax1 = max(V_tot1,[],'all');
    
    if (Vmax1>V_th)
        Vout = V_tot1;
        print("electrode-1");
    else
        V_tot2 = electrod2_stim(I_stim,ipi,pulse_width,dur,dt);
        Vmax2 =  max(V_tot2,[],'all');
        if(Vmax2>V_th)
            Vout = Vmax2;
            print("electrode-2");
        else
        V_tot_both = V_tot1 + V_tot2;
        Vmax_both =  max(V_tot_both,[],'all');
        
            if(Vmax_both>V_th)
                Vout = V_tot_both;
            else
                I_new = I_stim + 50;
            end
        end
    end

end

